scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["<Prometheus-server-address>:9090"]
  - job_name: 'express_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['<store-middleware-address>:3002']